---
settings:
  name: BlueXP remediation
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents de correction BlueXP
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez la résolution des problèmes BlueXP
      url: "/concept-resource-templates.html"
    - title: En savoir plus sur le balisage
      url: "/concept-tagging.html"
  - title: Utilisez la correction BlueXP
    entries:
    - title: Utilisez des modèles pour standardiser la création de ressources
      entries:
      - title: Créez des modèles pour votre entreprise
        url: "/task-define-templates.html"
      - title: Vérifier les ressources pour la conformité des modèles
        url: "/task-check-template-compliance.html"
      - title: Exécutez des modèles pour créer des ressources
        url: "/task-run-templates.html"
    - title: Organisez vos ressources à l'aide de balises
      entries:
      - title: Gérez les balises de vos ressources
        url: "/task-using-tags.html"
  - title: Concepts
    entries:
    - title: Éléments de base du modèle
      url: "/reference-template-building-blocks.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
